import "./globals.css";
import Script from "next/script";
import { Providers } from "@/components/Providers";
import { Header } from "@/components/mobile";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ko">
            <head>
                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20,300,0..1,0" />
                <Script
                    type="text/javascript"
                    src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_APP_KEY}&libraries=services&autoload=false`}
                    strategy="beforeInteractive"
                />
            </head>
            <Providers>
                <body>{children}</body>
            </Providers>
        </html>
    );
}
